# Generated by Django 6.0.2 on 2026-03-02 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(256)]),
        ),
    ]
